#+ endpoint: https://ubergraph.apps.renci.org/sparql
#+ defaults:
#+   - slim: http://purl.obolibrary.org/obo/uberon/core#major_organ
PREFIX in_subset: <http://www.geneontology.org/formats/oboInOwl#inSubset>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT  distinct ?term ?slim ?o ?label
WHERE
{
	?_term_iri ?_relation_iri ?o .
  	?o in_subset: ?_slim_iri .
    ?o rdfs:label ?label.
    bind(?_term_iri as ?term)
    bind(?_slim_iri as ?slim)
}

