#+ endpoint: https://ubergraph.apps.renci.org/sparql
#+ defaults:
#+   - slim: http://purl.obolibrary.org/obo/uberon/core#organ_slim
PREFIX in_subset: <http://www.geneontology.org/formats/oboInOwl#inSubset>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT  distinct ?term ?label
WHERE
{
	?_term_iri rdfs:subClassOf ?o .
  	?o in_subset: ?_slim_iri .
    ?_term_iri ?predicate ?label.
}